version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    environment:
      - COVERALLS_REPO_TOKEN: "K1nc8HCSTjEcbUqYg3dAw6AZOk958hlGZ"
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . .venv/bin/activate
            make test
            make cover
            make codecov
